version: '3.3'

services:
  redis-dlake:
    image: redis:5.0.5-alpine
    container_name: redis-dlake
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      iio:

  mongo-dlake:
    image: mongo:4
    container_name: mongo-dlake
    volumes:
      - /home/${USER}/iio-data/mongo:/data/db
    ports:
      - "40000:27017"
    networks:
      iio:

  dlake:
    image: ignitial/dlake:${APP_VERSION}
    container_name: dlake
    depends_on:
      - redis-dlake
      - mongo-dlake
    volumes:
      - ${PWD}:/opt/dlake
    ports:
      - "20990-20993:20990-20993"
    environment:
      - DEBUG=${DEBUG}
      - IIOS_REDIS_HOST=redis-dlake
      - IIOS_MONGODB_URI=mongodb://mongo-dlake:27017
      - IIOS_DBNAME=${IIOS_DBNAME}
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=dlake
      - IIOS_SERVER_PORT=20991
    networks:
      iio:

  alice:
    image: ignitial/dlake:${APP_VERSION}
    container_name: alice
    depends_on:
      - redis-dlake
    volumes:
      - ${PWD}:/opt/svc
    environment:
      - IIOS_SERVER_PORT=20991
      - IIOS_SERVER_HOST=alice
      - IIOS_NAMESPACE=dlaketests
      - IIOS_REDIS_HOST=redis-dlake
      - DEBUG=${DEBUG}
    command: ["node", "test/consumer/index.js"]
    networks:
      iio:

volumes:
  redis-data:

networks:
  iio:
